@startuml diagrame
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

' Styles
skinparam rectangle {
    BorderColor Black
    BorderStyle Dotted
    Padding 35
}

' Content
Container(mobileApp, "Mobile App", "React Native", "Provides notes manipulation options and a pleasant look for users.") #00546f

rectangle "API Application" as boundary {
    ' Controllers
    Component(accountController, "User Controller","C#", "Handles user authentication requests and manages user sessions.") #89CFF0
    Component(notesController, "Notes Controller","C#", "Manages requests related to notes, including creation, retrieval, and deletion.") #89CFF0
    Component(groupsController, "Groups Controller","C#", "Manages requests related to groups, including creation, members management, and deletion.") #89CFF0

    ' Services
    Component(services, "API Services", "C#", "Contains business logic for the actions requiered by controllers.") #89CFF0
}

ContainerDb(dataBase, "App Database", "Microsoft SQL Server", "Stores user details, notes, and specific tables to facilitate collections of notes.") #23282a

' Relationships
Rel(mobileApp, accountController, "Makes API calls to")
Rel(mobileApp, notesController, "Makes API calls to")
Rel(mobileApp, groupsController, "Makes API calls to")

Rel(accountController, services, "Solves requests using")
Rel(notesController, services, "Solves requests using")
Rel(groupsController, services, "Solves requests using")

Rel(services, dataBase, "Gets data from and stores to")
@enduml
