# This workflow will build and test a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  backend-build-and-test:
    name: Build and Test Backend
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore CollectifyAPI/CollectifyAPI/CollectifyAPI.csproj

    - name: Build
      run: dotnet build CollectifyAPI/CollectifyAPI/CollectifyAPI.csproj --no-restore

    - name: Test Backend Project
      run: dotnet test CollectifyAPI/CollectifyAPI/CollectifyAPI.csproj --no-build --verbosity normal

    - name: Test Unit and Integration Tests
      run: dotnet test CollectifyAPI.Tests/CollectifyAPI.Tests.csproj --no-build --verbosity normal
