name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  backend-build-and-test:
    name: Build and Unit Test Backend
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore CollectifyAPI/CollectifyAPI/CollectifyAPI.csproj

    - name: Build
      run: dotnet build CollectifyAPI/CollectifyAPI/CollectifyAPI.csproj --no-restore

    - name: Run Unit Tests
      run: dotnet test CollectifyAPI.Tests/ControllersTests --no-build --verbosity normal

  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    needs: backend-build-and-test

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore CollectifyAPI.Tests/IntegrationTests/IntegrationTests.csproj

    - name: Build
      run: dotnet build CollectifyAPI.Tests/IntegrationTests/IntegrationTests.csproj --no-restore

    - name: Run Integration Tests
      run: dotnet test CollectifyAPI.Tests/IntegrationTests --no-build --verbosity normal --logger trx

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: TestResults/
